@extends('layouts.app')
@section('title',$post->exists ? 'Chỉnh sửa bài viết' : 'Tạo bài viết')
@section('content')
<style>.editor-tools{display:flex;gap:6px;flex-wrap:wrap;padding:8px;border:1px solid #d0d5dd;border-bottom:0;border-radius:8px 8px 0 0;background:#f8fafc}.editor-tools button{border:1px solid #d0d5dd;background:#fff;border-radius:5px;padding:3px 8px;cursor:pointer}.rich-editor{min-height:240px;border:1px solid #d0d5dd;border-radius:0 0 8px 8px;padding:12px;background:#fff;outline:none}.rich-editor:empty:before{content:attr(data-placeholder);color:#98a2b3}.rich-editor h2,.rich-editor h3{margin:12px 0 7px}.rich-editor p{margin:0 0 10px}</style>
<div class="grid"><section class="panel"><form id="post-form" method="post" enctype="multipart/form-data" action="{{$post->exists ? route('posts.update',$post) : route('posts.store')}}">@csrf @if($post->exists) @method('PUT') @endif
@if($errors->any())<div class="errors">{{$errors->first()}}</div>@endif
<label>Tiêu đề / chủ đề</label><input id="title" name="title" value="{{old('title',$post->title)}}" placeholder="VD: 5 mẹo chăm sóc da mùa hè" required>
<div class="row"><div><label>Loại nội dung</label><select id="content_type" name="content_type"><option value="facebook" @selected(old('content_type',$post->content_type)==='facebook')>Bài đăng Facebook</option><option value="website" @selected(old('content_type',$post->content_type)==='website')>Bài viết website chuẩn SEO</option></select></div><div><label>Từ khóa SEO</label><input id="seo_keywords" name="seo_keywords" value="{{old('seo_keywords',$post->seo_keywords)}}" placeholder="VD: chăm sóc da, serum vitamin C"></div></div>
<label>CTA riêng cho bài này (tuỳ chọn)</label><input id="cta" name="cta" value="{{old('cta',$post->cta)}}" placeholder="VD: Gọi ngay 0901 234 567 để được tư vấn">
<div style="display:flex;justify-content:space-between;align-items:center"><label>Nội dung bài đăng</label><button type="button" id="generate-content" class="btn light small">✦ Tạo nội dung bằng Gemini</button></div>
<div class="editor-tools"><button type="button" data-cmd="bold"><b>B</b></button><button type="button" data-cmd="italic"><i>I</i></button><button type="button" data-cmd="underline"><u>U</u></button><button type="button" data-cmd="formatBlock" data-value="h2">H2</button><button type="button" data-cmd="formatBlock" data-value="h3">H3</button><button type="button" data-cmd="insertUnorderedList">• Danh sách</button><button type="button" data-cmd="insertOrderedList">1. Danh sách</button><button type="button" id="clear-format">Xóa định dạng</button></div>
<div id="rich-editor" class="rich-editor" contenteditable="true" data-placeholder="Nhập nội dung, hoặc bấm Tạo nội dung bằng Gemini...">{!! old('content',$post->content) !!}</div><textarea id="content" name="content" hidden required>{{old('content',$post->content)}}</textarea>
<div class="row"><div><label>Kết nối Facebook</label><select name="social_connection_id"><option value="">Chọn trang Facebook</option>@foreach($connections as $connection)<option value="{{$connection->id}}" @selected(old('social_connection_id',$post->social_connection_id)==$connection->id)>{{$connection->label}}</option>@endforeach</select></div><div><label>Chế độ xuất bản</label><select name="publish_mode"><option value="review" @selected(old('publish_mode',$post->publish_mode)==='review')>Chờ kiểm duyệt</option><option value="auto" @selected(old('publish_mode',$post->publish_mode)==='auto')>Đăng ngay</option><option value="schedule" @selected(old('publish_mode',$post->publish_mode)==='schedule')>Đặt lịch đăng</option></select></div></div>
<label>Thời gian đăng (khi đặt lịch)</label><input type="datetime-local" name="scheduled_at" value="{{old('scheduled_at',$post->scheduled_at?->format('Y-m-d\\TH:i'))}}">
<div style="display:flex;justify-content:space-between;align-items:center"><label>Gợi ý tạo hình ảnh bằng AI</label><button type="button" id="generate-image" class="btn light small">✦ Tạo hình ảnh từ nội dung</button></div><textarea id="image_prompt" style="min-height:75px" name="image_prompt" placeholder="Có thể nhập mô tả ảnh riêng, hoặc hệ thống sẽ tự dùng nội dung bài đăng.">{{old('image_prompt',$post->image_prompt)}}</textarea>
<label>Đường dẫn ảnh</label><input id="image_url" name="image_url" value="{{old('image_url',$post->image_url)}}" placeholder="Ảnh tạo bởi AI sẽ xuất hiện tại đây"><label>Tải ảnh từ máy tính</label><input id="image_file" name="image_file" type="file" accept="image/jpeg,image/png,image/webp"><span class="muted small">JPG, PNG hoặc WebP · tối đa 5 MB. Ảnh tải lên sẽ ưu tiên hơn URL.</span><div id="image-preview" style="margin-top:12px">@if($post->image_url)<img src="{{$post->image_url}}" alt="Ảnh bài viết" style="max-width:240px;border-radius:8px">@endif</div>
<div class="actions"><button class="btn light" name="action" value="save">Lưu bài viết</button><button class="btn green" name="action" value="publish" onclick="return confirm('Gửi bài này lên Facebook ngay?')">Gửi lên Facebook ngay</button>@if($post->exists)<a class="btn light" href="{{route('posts.index')}}">Quay lại</a>@endif</div></form></section>
<aside class="panel"><h2>Trợ lý AI</h2><p class="muted small">Gemini dùng loại nội dung, từ khóa SEO và hồ sơ thương hiệu để viết bài đúng mục đích.</p><div style="background:#f5f3ff;padding:14px;border-radius:9px" class="small"><strong>Quy trình</strong><br>1. Chọn Facebook hoặc Website SEO.<br>2. Nhập tiêu đề, từ khóa và CTA.<br>3. AI tạo bản nháp; chỉnh định dạng trước khi lưu.</div></aside></div>
<script>
const form=document.querySelector('#post-form'),csrf=form.querySelector('input[name=_token]').value,editor=document.querySelector('#rich-editor'),content=document.querySelector('#content');
function syncEditor(){content.value=editor.innerHTML;}
form.addEventListener('submit',syncEditor);editor.addEventListener('input',syncEditor);
document.querySelectorAll('[data-cmd]').forEach(b=>b.onclick=()=>{document.execCommand(b.dataset.cmd,false,b.dataset.value||null);editor.focus();syncEditor();});
document.querySelector('#clear-format').onclick=()=>{document.execCommand('removeFormat');editor.focus();syncEditor();};
async function runAi(url,payload,button){const old=button.textContent;button.disabled=true;button.textContent='Đang tạo...';try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':csrf},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.message||'Không thể tạo bằng AI.');return d;}catch(e){alert(e.message)}finally{button.disabled=false;button.textContent=old}}
document.querySelector('#generate-content').onclick=async function(){const title=document.querySelector('#title').value.trim();if(!title)return alert('Hãy nhập tiêu đề trước.');const d=await runAi('/posts/ai/gemini-content',{title,content_type:document.querySelector('#content_type').value,seo_keywords:document.querySelector('#seo_keywords').value,cta:document.querySelector('#cta').value},this);if(d?.content){editor.innerHTML=d.content;syncEditor();}};
document.querySelector('#generate-image').onclick=async function(){const title=document.querySelector('#title').value.trim();if(!title)return alert('Hãy nhập tiêu đề trước.');const d=await runAi('/posts/ai/image',{title,content:editor.innerText,image_prompt:document.querySelector('#image_prompt').value},this);if(d?.image_url){document.querySelector('#image_url').value=d.image_url;document.querySelector('#image_prompt').value=d.prompt;document.querySelector('#image-preview').innerHTML='<img src="'+d.image_url+'" alt="Ảnh AI" style="max-width:240px;border-radius:8px">';}};
document.querySelector('#image_file').onchange=function(){const file=this.files[0];if(file)document.querySelector('#image-preview').innerHTML='<img src="'+URL.createObjectURL(file)+'" alt="Ảnh xem trước" style="max-width:240px;border-radius:8px">';};
</script>
@endsection
